### ISSUE TITLE
TypeError: d.getUTCFullYear is not a function

### ISSUE THREAD

**Issue by natonnelier** [jpmonette/feed#59]
Hi, I'm following the documents in https://www.npmjs.com/package/feed but i still keep getting this error:
TypeError: d.getUTCFullYear is not a function
Could this be related to a null object? Which might be the problem?

**Comment by FreddyPoly** [comment]
Hi @natonnelier 

I don't know if our problems are related but using this package, I kept getting this error:

`TypeError: entry.date.toUTCString is not a function`

This error occured because I was adding items to my feed and filling the `date` field with a string as this one: `"2017-06-26T09:00+02:00"`

Actually, the package expects a Date format, so I had to reformat my string for it to fit expectations.
I did the following:

    feed.addItem({
          title: content.fields.title,
          id: content.sys.id,
          link: content.fields.url,
          description: content.fields.title,
          date: new Date(content.fields.publishedAt),
          image: content.fields.manualImage.fields.file.url,
    });

Maybe your error might be related to a Date format issue.

Hope it helps !

**Comment by fabionolasco** [comment]
Hi, I fixed that on my project by adding:
`date: new Date(post.pubDate)`

Hope it helps!

**Comment by QuanticPotatoes** [comment]
Hi !
Thx @fabionolasco !
I have also this error when i transformed my feed to Atom :
Now, it's fixed :smile: ! 
https://runkit.com/59958b7842151d0012cc155c/59958b7942151d0012cc155d

![image](https://user-images.githubusercontent.com/7420853/29414977-ba78f2d4-8361-11e7-97ea-e5192ab846cf.png)

**Comment by dmead** [comment]
this is still an issue.

anyone have luck fixing this? I'm trying `date: new Date()` and i've got no dice

**Comment by jpmonette** [comment]
If you set `date`, you must make sure to have some valid Date object assigned, otherwise Feed won't be able to process it correctly. Starting today, the codebase has been moved to TypeScript so hopefully it will be easier to flag for developers when types are wrong.
